### ISSUE TITLE
Backports drivers

### ISSUE THREAD

**Issue by raymerjacque** [SolydXK/device-driver-manager#11]
Does DDM check drivers in the backports repository ? I think not, since i had some users who's nvidia cards where drivers were not detected by driver manager and they installed drivers manually, when i investigated I saw they were installing from the jessie backports repository. Could the backports repository be added please ? or atleast the option to enable it ?

**Comment by raymerjacque** [comment]
O nevermind, i just saw when looking into the code there is a switch for backports :)

**Comment by ArjenBalfoort** [comment]
When using the GUI, just check the "Use backports" check box and when you run ddm without a GUI, add the -b argument. Check "ddm -h" for all arguments.
